### ISSUE TITLE
PA Review - Profile

### ISSUE THREAD

**Issue by trwong** [trwong/fakebook#4]
- [x] Backend: DB, model, controller, views
- [x] Redux loop: ajax, actions, reducers
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by ajansel** [comment]
Awesome work! I had a few thoughts: 
- The guest login should probably have a default cover and profile photo 
- There should be a pointer hover effect when the user hovers over 'update profile picture' or 'update cover photo' to add some nice styling and so that it isn't confusing where they should click
- When I post on someone's wall the font size seems to be different than the other posts on the wall

**Comment by trwong** [comment]
I've resolved the first two bullet points locally.

Different font sizes was intentional. Facebook enlarges the font size on posts under 85 characters. I do think it looks inconsistent, especially for people not familiar with Facebook. Do you think I should remove it?

**Comment by ajansel** [comment]
Awesome, good work! Hmmm great point. I never realized this.. Personally I
think that's often overlooked and it would look better keeping it all the
same font. But, that's just my opinion. I will leave it up to you what
you'd like to do since technically FB does that too!

**Comment by trwong** [comment]
I've created issues for each item and resolved all but the font sizing.
